# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

  ghost:
    image: ghost:4.4.0
    restart: always
    ports:
      - 80:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: Z#[?DpFp3q4_#]dj
      database__connection__database: dongkamkan
      url: http://dongkamkan.com
      NODE_ENV: production

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Z#[?DpFp3q4_#]dj

  myadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80

volumes:
  db_data:
    external: true